version: "3.9"

services:
  server:
    build: ./backend
    container_name: crypto-predict
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    networks:
      - prediction
    restart: unless-stopped    

  client:
    build: ./frontend
    container_name: crypto-predict-frontend
    ports:
      - "5174:3000"
    networks:
      - prediction
    depends_on:
      - server
    restart: unless-stopped    

networks:
  prediction:
    driver: bridge
